#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
server:
  port: 8082



spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rootroot
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
      
okta:
  oauth2:
    issuer: https://dev-89582867.okta.com/oauth2/default
    audience: api://default 
