#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true



server:
  port: 8081


spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rootroot
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-89582867.okta.com/oauth2/default
      client:
        registration:
          my-internal-client: 
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaapv7m7v4NknsWP5d7
            client-secret: LWGsKrBw-wBX26lw0johCfh9wV9A_weCTO7Y0gk-2muQHFkln_UESV7_WK5U8GZ5
        provider:
          okta:
            issuer-uri: https://dev-89582867.okta.com/oauth2/default
    
 

    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health      
  endpoint:
    health:
      show-details: always
      
      
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:  6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
        
  ratelimiter:  # need to download Apache JMeter for testing purpose
    instances:
      userRateLimiter:
        limit-refresh-period:  4s
        limit-for-period: 2
        timeout-duration: 0s
 
 
okta:
  oauth2:
    issuer: https://dev-89582867.okta.com/oauth2/default
    audience: api://default   
      
      
      
      

        
  
    
    






    